### PR TITLE
feat: Accordion

### PR DESCRIPTION
**Pull request by cobraz**
Adds a nice accordion

### Tasks

- [ ] ~~Needs the arrow up and down (only say «Clicky» atm)~~ (removed from design)
- [ ] ARIA stuff

### CODE REVIEW

**Comment by braaar** [comment]
First impressions: I like the look, but I wonder whether we would want som option for removing the separator line. There might be a scenario where one would want to contrast the header and the content with differently coloured backgrounds

**Comment by cobraz** [comment]
> First impressions: I like the look, but I wonder whether we would want som option for removing the separator line. There might be a scenario where one would want to contrast the header and the content with differently coloured backgrounds

Ah! You're right, we should probably not include it at all?

**Comment by braaar** [comment]
What happened to the arrow?

**Comment by cobraz** [comment]
> What happened to the arrow?

It died. At least for now 😅

**Comment by braaar** [comment]
Features I would have liked to see that are missing (could be added in a later version)
- Option to not show the separator line
- Option to fill the child boxes with a colour of your choice (so that we can replicate a design similar to the old style)
Screenshot 2021-11-25 at 9 36 42

Currently I get this when trying to do something like that ( `width` and `height` set to `100%`):
Screenshot 2021-11-25 at 9 37 54

**Comment by braaar** [comment]
Screenshot 2021-11-25 at 9 41 03

Hard corners when filling boxes with colour. Shouldn't the accordion enforce rounded corners?

**Review by braaar — APPROVED** [review]

**Pull request merged**
